### ISSUE TITLE
Similar project inspired by this app

### ISSUE THREAD

**Issue by uwla** [KeziahMoselle/export-github-stars#12]
Hello, thanks for the awesome project.

It really enjoyed this project! Recently, I decide to make a similar project, but aimed to organize starred repositories from various sources (github, gitlab, gitea, gogs, etc) and with little more features.

[Starred Repos Organizer](https://github.com/uwla/starred_repos_organizer)

Can I link your project in my project's README? To give you some credits for the inspiration

**Comment by KeziahMoselle** [comment]
Cool project!
Sure you can :)

**Comment by uwla** [comment]
Done :)
